import { Component, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { AuthService } from '../../../../core/services/auth.service';
import { NotificacionService } from '../../../../core/services/notificacion.service';
import { IconComponent } from '../../../../shared/icon/icon.component';

@Component({selector:'app-configuracion-admin',standalone:true,imports:[FormsModule,IconComponent],template:`<div class="page-shell"><header class="page-header"><div><span class="eyebrow">Preferencias</span><h1>Configuración</h1><p>Controla cómo recibes los avisos del sistema.</p></div></header><div class="settings-grid"><section class="surface"><h2>Notificaciones</h2><p>Elige qué novedades deben llegar a este dispositivo.</p>@for(item of items;track item.label){<label class="setting"><span class="setting-icon"><app-icon [name]="item.icon" [size]="20"/></span><span><strong>{{item.label}}</strong><small>{{item.description}}</small></span><span class="switch"><input type="checkbox" [(ngModel)]="item.enabled"><span class="switch-track"></span></span></label>}<button class="btn btn-primary" (click)="save()">Guardar preferencias</button></section><section class="surface account"><h2>Cuenta</h2><div class="user"><span>DP</span><div><strong>Daniel Pérez</strong><small>daniel&#64;salud.ec</small></div></div><button class="btn btn-danger" (click)="logout()"><app-icon name="logout" [size]="18"/> Cerrar sesión</button></section></div></div>`,styles:[`.settings-grid{display:grid;gap:18px}.surface{padding:20px}.surface h2{margin:0 0 5px;font-size:1rem}.surface>p{color:var(--text-muted);font-size:.75rem;margin-bottom:20px}.setting{display:grid;grid-template-columns:auto minmax(0,1fr) auto;align-items:center;gap:11px;padding:15px 0;border-top:1px solid var(--border)}.setting-icon{width:39px;height:39px;display:grid;place-items:center;border-radius:11px;background:var(--primary-soft);color:var(--primary)}.setting strong,.setting small{display:block}.setting strong{font-size:.78rem}.setting small{margin-top:3px;color:var(--text-muted);font-size:.68rem}.surface>.btn{margin-top:18px}.user{display:flex;align-items:center;gap:12px;padding:18px 0}.user>span{width:48px;height:48px;border-radius:50%;display:grid;place-items:center;background:var(--primary-soft);color:var(--primary);font-weight:850}.user strong,.user small{display:block}.user small{margin-top:4px;color:var(--text-muted);font-size:.72rem}.account .btn{width:100%}@media(min-width:800px){.settings-grid{grid-template-columns:minmax(0,1fr) 300px;align-items:start}.surface{padding:25px}.account{position:sticky;top:98px}}`]
})
export class ConfiguracionAdminComponent {private readonly notify=inject(NotificacionService);private readonly auth=inject(AuthService);private readonly router=inject(Router);items=[{label:'Alertas críticas',description:'SpO₂ baja o pulsaciones fuera de rango.',icon:'alert',enabled:true},{label:'Medicamentos pendientes',description:'Tomas que todavía no fueron confirmadas.',icon:'pill',enabled:true},{label:'Estado del dispositivo',description:'Desconexiones o conexiones inusuales.',icon:'wifi',enabled:true}];save(){this.notify.mostrar('Preferencias guardadas');}logout(){this.auth.logout();this.router.navigate(['/login']);}}

