import { Component, Input } from '@angular/core';
import { IconComponent } from '../../../../shared/icon/icon.component';

export interface MetricaResumen { label: string; value: string; detail: string; icon: string; tone: 'primary' | 'secondary' | 'warning'; }

@Component({
  selector: 'app-resumen-salud', standalone: true, imports: [IconComponent],
  template: `<section aria-labelledby="resumen-title"><h2 id="resumen-title">Resumen de hoy</h2><div class="metrics">@for(metric of metrics; track metric.label; let i=$index){<article class="metric" [style.--delay.ms]="i*55"><span class="metric-icon" [class]="metric.tone"><app-icon [name]="metric.icon" [size]="22" /></span><div><small>{{metric.label}}</small><strong>{{metric.value}}</strong><span>{{metric.detail}}</span></div></article>}</div></section>`,
  styles: [`:host{display:block;min-width:0;max-width:100%}h2{font-size:1rem;margin:0 0 13px}.metrics{width:100%;min-width:0;display:grid;grid-auto-flow:column;grid-auto-columns:132px;gap:10px;overflow-x:auto;scroll-snap-type:x mandatory;overscroll-behavior-inline:contain;padding:1px 1px 12px}.metric{scroll-snap-align:start;min-height:126px;padding:16px 14px;display:flex;flex-direction:column;justify-content:space-between;background:white;border:1px solid var(--border);border-radius:16px;box-shadow:var(--shadow-small);animation:rise .45s cubic-bezier(.16,1,.3,1) both;animation-delay:var(--delay)}.metric>div{display:grid}.metric small{height:30px;color:var(--text);font-size:.68rem;font-weight:750;line-height:1.25}.metric strong{font-size:1.5rem;letter-spacing:-.04em;line-height:1.1}.metric span:not(.metric-icon){margin-top:3px;color:var(--text-muted);font-size:.65rem}.metric-icon{width:35px;height:35px;display:grid;place-items:center;border-radius:11px;margin-bottom:10px}.metric-icon.primary{color:var(--primary);background:var(--primary-soft)}.metric-icon.secondary{color:var(--secondary);background:var(--info-soft)}.metric-icon.warning{color:var(--warning);background:var(--warning-soft)}@keyframes rise{from{opacity:0;transform:translateY(8px)}}@media(min-width:1000px){.metrics{grid-template-columns:repeat(5,minmax(0,1fr));grid-auto-flow:initial;overflow:visible;padding-bottom:0}.metric{min-height:118px;display:grid;grid-template-columns:auto 1fr;align-items:center;gap:10px}.metric-icon{margin:0}.metric small{height:28px}.metric strong{font-size:1.45rem}}`]
})
export class ResumenSaludComponent { @Input({ required: true }) metrics: MetricaResumen[] = []; }
